KerbalStuff/blueprints/admin.py
from flask import Blueprint, render_template, abort, redirect
from flask.ext.login import current_user
from sqlalchemy import desc
from KerbalStuff.objects import User, Mod, GameVersion
from KerbalStuff.database import db
from KerbalStuff.common import *
from KerbalStuff.email import send_bulk_email
from flask.ext.login import current_user, login_user, logout_user

admin = Blueprint('admin', __name__, template_folder='../../templates/admin')

@admin.route("/admin")
@adminrequired
def backend():
    users = User.query.count()
    new_users = User.query.order_by(desc(User.created)).limit(24)
    mods = Mod.query.count()
    versions = GameVersion.query.order_by(desc(GameVersion.id)).all()
    return render_template("admin.html", users=users, mods=mods, new_users=new_users, versions=versions)

@admin.route("/admin/impersonate/<username>")
@adminrequired
def impersonate(username):
    user = User.query.filter(User.username == username).first()
    login_user(user)
    return redirect("/")

@admin.route("/versions/create", methods=['POST'])
@adminrequired
@with_session
def create_version():
    friendly = request.form.get("friendly_version")
    if not friendly:
        return redirect("/asdf")
    if any(GameVersion.query.filter(GameVersion.friendly_version == friendly)):
        return redirect("/fsda")
    version = GameVersion(friendly)
    db.add(version)
    db.commit()
    return redirect("/admin")

@admin.route("/admin/email", methods=['POST'])
@adminrequired
def email():
    subject = request.form.get('subject')
    body = request.form.get('body')
    modders_only = request.form.get('modders-only') == 'on'
    if not subject or not body:
        abort(400)
    if subject == '' or body == '':
        abort(400)
    users = User.query.all()
    if modders_only:
        users = [u for u in users if len(u.mods) != 0 or u.username == current_user.username]
    send_bulk_email([u.email for u in users], subject, body)
    return redirect("/admin")

@admin.route("/admin/manual-confirmation/<user_id>")
@adminrequired
@with_session
def manual_confirm(user_id):
    user = User.query.filter(User.id == int(user_id)).first()
    if not user:
        abort(404)
    user.confirmation = None
    return redirect("/profile/" + user.username)

KerbalStuff/blueprints/blog.py
from flask import Blueprint, render_template, abort
from KerbalStuff.objects import User, BlogPost
from KerbalStuff.database import db
from KerbalStuff.common import *

blog = Blueprint('blog', __name__, template_folder='../../templates/blog')

@blog.route("/blog")
def index():
    posts = BlogPost.query.all()
    return render_template("blog_index.html", posts=posts)

@blog.route("/blog/post", methods=['POST'])
@adminrequired
@with_session
def post_blog():
    title = request.form.get('post-title')
    body = request.form.get('post-body')
    post = BlogPost()
    post.title = title
    post.text = body
    db.add(post)
    db.commit()
    return redirect("/blog/" + str(post.id))

@blog.route("/blog/<id>/edit", methods=['GET', 'POST'])
@adminrequired
@with_session
def edit_blog(id):
    post = BlogPost.query.filter(BlogPost.id == id).first()
    if not post:
        abort(404)
    if request.method == 'GET':
        return render_template("edit_blog.html", post=post)
    else:
        title = request.form.get('post-title')
        body = request.form.get('post-body')
        post.title = title
        post.text = body
        return redirect("/blog/" + str(post.id))

@blog.route("/blog/<id>/delete", methods=['POST'])
@adminrequired
@json_output
@with_session
def delete_blog(id):
    post = BlogPost.query.filter(BlogPost.id == id).first()
    if not post:
        abort(404)
    db.delete(post)
    return redirect("/")

@blog.route("/blog/<id>")
def view_blog(id):
    post = BlogPost.query.filter(BlogPost.id == id).first()
    if not post:
        abort(404)
    return render_template("blog.html", post=post)

KerbalStuff/blueprints/mods.py
from flask import Blueprint, render_template, request, g, Response, redirect, session, abort, send_file, make_response, url_for
from flask.ext.login import current_user
from sqlalchemy import desc
from KerbalStuff.objects import User, Mod, ModVersion, DownloadEvent, FollowEvent, ReferralEvent, Featured, Media, GameVersion
from KerbalStuff.email import send_update_notification, send_autoupdate_notification
from KerbalStuff.database import db
from KerbalStuff.common import *
from KerbalStuff.config import _cfg
from KerbalStuff.blueprints.api import default_description
from KerbalStuff.ckan import send_to_ckan
from werkzeug.utils import secure_filename
from datetime import datetime, timedelta
from shutil import rmtree, copyfile
from urllib.parse import urlparse

import os
import zipfile
import urllib
import random

mods = Blueprint('mods', __name__, template_folder='../../templates/mods')

@mods.route("/random")
def random_mod():
    mods = Mod.query.filter(Mod.published == True).all()
    mod = random.choice(mods)
    return redirect(url_for("mods.mod", id=mod.id, mod_name=mod.name))

@mods.route("/mod/<int:id>/<path:mod_name>/update")
def update(id, mod_name):
    mod = Mod.query.filter(Mod.id == id).first()
    if not mod:
        abort(404)
    editable = False
    if current_user.admin:
        editable = True
    if current_user.id == mod.user_id:
        editable = True
    if any([u.accepted and u.user == current_user for u in mod.shared_authors]):
        editable = True
    if not editable:
        abort(401)
    return render_template("update.html", mod=mod, game_versions=GameVersion.query.order_by(desc(GameVersion.id)).all())

@mods.route("/mod/<int:id>.rss", defaults={'mod_name': None})
@mods.route("/mod/<int:id>/<path:mod_name>.rss")
def mod_rss(id, mod_name):
    mod = Mod.query.filter(Mod.id == id).first()
    if not mod:
        abort(404)
    return render_template("rss-mod.xml", mod=mod)

@mods.route("/mod/<int:id>", defaults={'mod_name': None})
@mods.route("/mod/<int:id>/<path:mod_name>")
@with_session
def mod(id, mod_name):
    mod = Mod.query.filter(Mod.id == id).first()
    if not mod:
        abort(404)
    editable = False
    if current_user:
        if current_user.admin:
            editable = True
        if current_user.id == mod.user_id:
            editable = True
    if not mod.published and not editable:
        abort(401)
    latest = mod.default_version()
    referral = request.referrer
    if referral:
        host = urllib.parse.urlparse(referral).hostname
        event = ReferralEvent.query\
                .filter(ReferralEvent.mod_id == mod.id)\
                .filter(ReferralEvent.host == host)\
                .first()
        if not event:
            event = ReferralEvent()
            event.mod = mod
            event.events = 1
            event.host = host
            db.add(event)
            db.flush()
            db.commit()
            mod.referrals.append(event)
        else:
            event.events += 1
    download_stats = None
    follower_stats = None
    referrals = None
    json_versions = None
    thirty_days_ago = datetime.now() - timedelta(days=30)
    referrals = list()
    for r in ReferralEvent.query\
        .filter(ReferralEvent.mod_id == mod.id)\
        .order_by(desc(ReferralEvent.events)):
        referrals.append( { 'host': r.host, 'count': r.events } )
    download_stats = list()
    for d in DownloadEvent.query\
        .filter(DownloadEvent.mod_id == mod.id)\
        .filter(DownloadEvent.created > thirty_days_ago)\
        .order_by(DownloadEvent.created):
        download_stats.append(dumb_object(d))
    follower_stats = list()
    for f in FollowEvent.query\
        .filter(FollowEvent.mod_id == mod.id)\
        .filter(FollowEvent.created > thirty_days_ago)\
        .order_by(FollowEvent.created):
        follower_stats.append(dumb_object(f))
    json_versions = list()
    for v in mod.versions:
        json_versions.append({ 'name': v.friendly_version, 'id': v.id })
    if request.args.get('noedit') != None:
        editable = False
    forumThread = False
    if mod.external_link != None:
        try:
            u = urlparse(mod.external_link)
            if u.netloc == 'forum.kerbalspaceprogram.com':
                forumThread = True
        except e:
            print(e)
            pass
    total_authors = 1
    pending_invite = False
    owner = editable
    for a in mod.shared_authors:
        if a.accepted:
            total_authors += 1
        if current_user:
            if current_user.id == a.user_id and not a.accepted:
                pending_invite = True
            if current_user.id == a.user_id and a.accepted:
                editable = True
    game_versions = GameVersion.query.order_by(desc(GameVersion.id)).all()
    outdated = False
    if latest:
        outdated = game_versions[0].friendly_version != latest.ksp_version
    return render_template("mod.html",
        **{
            'mod': mod,
            'latest': latest,
            'safe_name': secure_filename(mod.name)[:64],
            'featured': any(Featured.query.filter(Featured.mod_id == mod.id).all()),
            'editable': editable,
            'owner': owner,
            'pending_invite': pending_invite,
            'download_stats': download_stats,
            'follower_stats': follower_stats,
            'referrals': referrals,
            'json_versions': json_versions,
            'thirty_days_ago': thirty_days_ago,
            'share_link': urllib.parse.quote_plus(_cfg("protocol") + "://" + _cfg("domain") + "/mod/" + str(mod.id)),
            'game_versions': game_versions,
            'outdated': outdated,
            'forum_thread': forumThread,
            'new': request.args.get('new') != None,
            'stupid_user': request.args.get('stupid_user') != None,
            'total_authors': total_authors
        })

@mods.route("/mod/<int:id>/<path:mod_name>/edit", methods=['GET', 'POST'])
@with_session
@loginrequired
def edit_mod(id, mod_name):
    mod = Mod.query.filter(Mod.id == id).first()
    if not mod:
        abort(404)
    editable = False
    if current_user.admin:
        editable = True
    if current_user.id == mod.user_id:
        editable = True
    if any([u.accepted and u.user == current_user for u in mod.shared_authors]):
        editable = True
    if not editable:
        abort(401)
    if request.method == 'GET':
        return render_template("edit_mod.html", mod=mod, original=mod.user == current_user)
    else:
        short_description = request.form.get('short-description')
        license = request.form.get('license')
        donation_link = request.form.get('donation-link')
        external_link = request.form.get('external-link')
        source_link = request.form.get('source-link')
        description = request.form.get('description')
        background = request.form.get('background')
        bgOffsetY = request.form.get('bg-offset-y')
        if not license or license == '':
            return render_template("edit_mod.html", mod=mod, error="All mods must have a license.")
        mod.short_description = short_description
        mod.license = license
        mod.donation_link = donation_link
        mod.external_link = external_link
        mod.source_link = source_link
        mod.description = description
        if background and background != '':
            mod.background = background
        try:
            mod.bgOffsetY = int(bgOffsetY)
        except:
            pass
        return redirect(url_for("mods.mod", id=mod.id, mod_name=mod.name))

@mods.route("/create/mod")
@loginrequired
@with_session
def create_mod():
    return render_template("create.html", game_versions=GameVersion.query.order_by(desc(GameVersion.id)).all())

@mods.route("/mod/<int:mod_id>/stats/downloads", defaults={'mod_name': None})
@mods.route("/mod/<int:mod_id>/<path:mod_name>/stats/downloads")
def export_downloads(mod_id, mod_name):
    mod = Mod.query.filter(Mod.id == mod_id).first()
    if not mod:
        abort(404)
    download_stats = DownloadEvent.query\
        .filter(DownloadEvent.mod_id == mod.id)\
        .order_by(DownloadEvent.created)
    response = make_response(render_template("downloads.csv", stats=download_stats))
    response.headers['Content-Type'] = 'text/csv'
    response.headers['Content-Disposition'] = 'attachment;filename=downloads.csv'
    return response

@mods.route("/mod/<int:mod_id>/stats/followers", defaults={'mod_name': None})
@mods.route("/mod/<int:mod_id>/<path:mod_name>/stats/followers")
def export_followers(mod_id, mod_name):
    mod = Mod.query.filter(Mod.id == mod_id).first()
    if not mod:
        abort(404)
    follower_stats = FollowEvent.query\
        .filter(FollowEvent.mod_id == mod.id)\
        .order_by(FollowEvent.created)
    response = make_response(render_template("followers.csv", stats=follower_stats))
    response.headers['Content-Type'] = 'text/csv'
    response.headers['Content-Disposition'] = 'attachment;filename=followers.csv'
    return response

@mods.route("/mod/<int:mod_id>/stats/referrals", defaults={'mod_name': None})
@mods.route("/mod/<mod_id>/<path:mod_name>/stats/referrals")
def export_referrals(mod_id, mod_name):
    mod = Mod.query.filter(Mod.id == mod_id).first()
    if not mod:
        abort(404)
    referral_stats = ReferralEvent.query\
            .filter(ReferralEvent.mod_id == mod.id)\
            .order_by(desc(ReferralEvent.events))
    response = make_response(render_template("referrals.csv", stats=referral_stats))
    response.headers['Content-Type'] = 'text/csv'
    response.headers['Content-Disposition'] = 'attachment;filename=referrals.csv'
    return response

@mods.route("/mod/<int:mod_id>/delete", methods=['POST'])
@loginrequired
@with_session
def delete(mod_id):
    mod = Mod.query.filter(Mod.id == mod_id).first()
    if not mod:
        abort(404)
    editable = False
    if current_user:
        if current_user.admin:

KerbalStuff/blueprints/profile.py
from flask import Blueprint, render_template, abort
from flask.ext.login import current_user
from KerbalStuff.objects import User
from KerbalStuff.database import db
from KerbalStuff.common import *

profiles = Blueprint('profile', __name__, template_folder='../../templates/profiles')

@profiles.route("/profile/<username>")
def view_profile(username):
    user = User.query.filter(User.username == username).first()
    if not user:
        abort(404)
    if not user.public:
        if not current_user:
            abort(401)
        if current_user.username != user.username:
            if not current_user.admin:
                abort(401)
    mods_created = sorted(user.mods, key=lambda mod: mod.created, reverse=True)
    if not current_user or current_user.id != user.id:
        mods_created = [mod for mod in mods_created if mod.published]
    mods_followed = sorted(user.following, key=lambda mod: mod.created, reverse=True)
    return render_template("view_profile.html", **{ 'profile': user, 'mods_created': mods_created, 'mods_followed': mods_followed })

@profiles.route("/profile/<username>/edit", methods=['GET', 'POST'])
@loginrequired
@with_session
def profile(username):
    if request.method == 'GET':
        profile = User.query.filter(User.username == username).first()
        if not profile:
            abort(404)
        if current_user != profile and not current_user.admin:
            abort(403)
        return render_template("profile.html", **{ 'profile': profile })
    else:
        profile = User.query.filter(User.username == username).first()
        if not profile:
            abort(404)
        if current_user != profile and not current_user.admin:
            abort(403)
        profile.redditUsername = request.form.get('reddit-username')
        profile.description = request.form.get('description')
        profile.twitterUsername = request.form.get('twitter')
        profile.forumUsername = request.form.get('ksp-forum-user')
        result = getForumId(profile.forumUsername)
        if not result:
            profile.forumUsername = ''
        else:
            profile.forumUsername = result['name']
            profile.forumId = result['id']
        profile.ircNick = request.form.get('irc-nick')
        profile.backgroundMedia = request.form.get('backgroundMedia')
        bgOffsetX = request.form.get('bg-offset-x')
        bgOffsetY = request.form.get('bg-offset-y')
        if bgOffsetX:
            profile.bgOffsetX = int(bgOffsetX)
        if bgOffsetY:
            profile.bgOffsetY = int(bgOffsetY)
        return redirect("/profile/" + profile.username)

@profiles.route("/profile/<username>/make-public", methods=['POST'])
@loginrequired
@with_session
def make_public(username):
    if current_user.username != username:
        abort(401)
    current_user.public = True
    return redirect("/profile/" + current_user.username)

templates/anniversary.html
{% extends "layout.html" %}
{% block styles %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='anniversary.css') }}" />
{% endblock %}
{% block body %}
<div class="header">
    <div class="vert-text">
        <h3>One year of Kerbal Stuff</h3>
        <p>Kerbal Stuff was <a
            href="http://forum.kerbalspaceprogram.com/threads/71133-Community-Mod-Repository-and-The-Majiir-Challenge?p=1187833&viewfull=1#post1187833">introduced</a>
            to the world on June 1st, 2014, with the singular goal of providing a better solution than Curse.</p>
    </div>
</div>
<div id="players">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h2><i class="fa fa-rocket"></i> {{ mods }} mods <small>216 more than Curse!</small></h2>
            </div>
            <div class="col-md-4">
                <h2 class="text-right">{{ "{:,}".format(users) }} users <i class="fa fa-users"></i></h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <h2><i class="fa fa-envelope"></i> ~250,000 update notifications sent</h2>
            </div>
            <div class="col-md-6">
                <h2 class="text-right">{{ "{:,}".format(downloads) }} total downloads <i class="fa fa-download"></i></h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <h2><i class="fa fa-bar-chart"></i> 483,051 unique visitors <small>109,525 in May!</small></h2>
            </div>
            <div class="col-md-6">
                <h2 class="text-right">7,687,155 page views <i class="fa fa-eye"></i></h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <h2><i class="fa fa-clock-o"></i> 2 minutes, 27 seconds <small>per average visit</small></h2>
            </div>
            <div class="col-md-6">
                <h2 class="text-right">3.4 average pages per visit <i class="fa fa-book"></i></h2>
            </div>
        </div>
        <p class="text-muted text-center" style="color: #666; margin-bottom: 0;"><small>In case you hadn't guessed, some of these stats are not live.</small></p>
    </div>
</div>
<div class="well well-sm" style="margin-bottom: 0">
    <div class="container">
        <p style="padding-top: 7px;">Kerbal Stuff is fortunate to host several popular mods. Here's the top 6 mods on Kerbal Stuff:</p>
    </div>
</div>
<div id="modders">
    <div class="container" style="padding-top: 10px">
        <div class="row">
        {% for mod in top %}
        {% include "featured-mod-box.html" %}
        {% endfor %}
        </div>
    </div>
</div>
<div class="well well-sm" style="margin-bottom: 0">
    <div class="container">
        <p style="padding-top: 7px;">This website didn't become successful overnight. Thanks to our early adopters - here's the oldest mods on KS, some from the day the public beta opened:</p>
    </div>
</div>
<div id="modders">
    <div class="container" style="padding-top: 10px">
        <div class="row">
        {% for mod in oldest %}
        {% include "featured-mod-box.html" %}
        {% endfor %}
        </div>
    </div>
</div>
<div class="well well-sm" style="margin-bottom: 0">
    <div class="container">
        <p style="padding-top: 7px;">Kerbal Stuff is awesome, and it's thanks to the users and modders that it can be. Thank you for your support.</p>
    </div>
</div>
<div id="register">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4 centered">
                <h1>One year of...</h1>
                <hr />
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 centered">
                <div class="service-icon"><i class="fa fa-eye" style="position: relative; top: -5px"></i></div>
                <h3>No advertisements</h3>
            </div>
            <div class="col-md-3 centered">
                <div class="service-icon"><i class="fa fa-envelope" style="position: relative; top: -5px"></i></div>
                <h3>Emailing updates</h3>
            </div>
            <div class="col-md-3 centered">
                <div class="service-icon"><i class="fa fa-git" style="position: relative; top: -5px"></i></div>
                <h3>Open Source</h3>
            </div>
            <div class="col-md-3 centered">
                <div class="service-icon"><i class="fa fa-archive" style="position: relative; top: -5px"></i></div>
                <h3>CKAN</h3>
            </div>
            <div class="col-md-3 centered">
                <div class="service-icon"><i class="fa fa-line-chart" style="position: relative; top: -5px"></i></div>
                <h3>Powerful stats</h3>
            </div>
            <div class="col-md-3 centered">
                <div class="service-icon"><i class="fa fa-clock-o" style="position: relative; top: -5px"></i></div>
                <h3>Immediate updates</h3>
            </div>
            <div class="col-md-3 centered">
                <div class="service-icon"><i class="fa fa-search" style="position: relative; top: -5px"></i></div>
                <h3>Usable search</h3>
            </div>
            <div class="col-md-3 centered">
                <div class="service-icon"><i class="fa fa-rocket" style="position: relative; top: -5px"></i></div>
                <h3>Great mods!</h3>
            </div>
        </div>
    </div>
</div>
<div class="well well-sm" style="margin-bottom: 0">
    <div class="container">
        <h1 class="text-center">Let's have another great year!</h1>
        <p class="text-center">With love, SirCmpwn</p>
        <p class="text-center">
            <img src="/static/signature.png" />
        </p>
    </div>
</div>
{% endblock %}

templates/error.html
Error

templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/vnd.microsoft.icon" href="/static/icon.ico">
        <link rel="stylesheet" href="//cdn.jsdelivr.net/editor/0.1.0/editor.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <link rel="search" type="application/opensearchdescription+xml" title="KerbalStuff" href="/static/opensearch.xml" />
        <meta property="og:image" content="/static/logo.png" />
        {% block title %}
        <title>Kerbal Stuff</title>
        {% endblock %}
        <link href="/static/bootstrap.min.css" rel="stylesheet">
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        {% block styles %}{% endblock %}
    </head>
    <body class="{% if user %}logged-in{% endif %}">
        {% block nav %}
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation" {% if user and user.admin %}style="background: #FF5555;"{% endif %}>
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/"><img src="/static/logo.png" /> Kerbal Stuff</a>
                    {% if admin %}
                    <p class="navbar-text" style="color: white">Administrator</p>
                    {% endif %}
                </div>
                <div class="collapse navbar-collapse" id="navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li><a href="/random">Random Mod</a></li>
                    </ul>
                    {% if not user %}
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{{ url_for("accounts.register") }}">Register</a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Log In <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <form role="form" action="/login" method="POST">
                                    <input type="text" id="username" placeholder="Username" name="username">
                                    <input type="password" id="password" placeholder="Password" name="password">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="remember-me" id="remember-me">
                                            Remember Me
                                        </label>
                                    </div>
                                    <input type="hidden" name="return_to" value="{{ request.path }}">
                                    <input type="submit" value="Log In" class="btn btn-primary">
                                </form>
                                <li class="divider"></li>
                                <li>
                                    <a href="{{ url_for("accounts.forgot_password") }}">
                                        <span class="glyphicon glyphicon-question-sign"></span> Forgot Password
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    {% else %}
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome, {{ user.username }} <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="/create/mod">
                                        <span class="glyphicon glyphicon-open"></span> Create a New Mod
                                    </a>
                                </li>
                                <li>
                                    <a href="/create/pack">
                                        <span class="glyphicon glyphicon-list"></span> Create a New Pack
                                    </a>
                                </li>
                                <li>
                                    <a href="{{ url_for("profile.view_profile", username=user.username) }}">
                                        <span class="glyphicon glyphicon-user"></span> View Your Profile
                                    </a>
                                </li>
                                <li>
                                    <a href="{{ url_for("profile.profile", username=user.username) }}">
                                        <span class="glyphicon glyphicon-pencil"></span> Edit Your Profile
                                    </a>
                                </li>
                                {% if admin %}
                                <li>
                                    <a href="{{ url_for("admin.backend") }}">
                                        <span class="glyphicon glyphicon-fire"></span> Admin Stuff
                                    </a>
                                </li>
                                {% endif %}
                                <li>
                                    <a href="{{ url_for("accounts.logout") }}">
                                        <span class="glyphicon glyphicon-remove"></span> Log Out
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    {% endif %}
                    {% block search %}
                    <form class="navbar-form navbar-search" role="search" action="/search" method="GET">
                        <div class="form-group">
                            <input type="text" class="form-control search-box" name="query" placeholder="Search mods...">
                        </div>
                    </form>
                    {% endblock %}
                </div>
            </div>
        </nav>
        {% endblock %}
        <div class="alert alert-info alert-dismissable alert-fixed hidden" id="alert-follow">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Done!</strong> You'll get emailed updates for this mod.
        </div>
        {% block body %}{% endblock %}
        <footer>
            <div class="container centered">
                <hr />
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="nav nav-pills nav-justified">
                            <li><a href="https://github.com/KerbalStuff/KerbalStuff">Source Code</a></li>
                            <li><a href="https://github.com/KerbalStuff/KerbalStuff/blob/master/api.md">API</a></li>
                            <li><a href="/privacy">Terms & Privacy</a></li>
                            <li><a href="mailto:support@kerbalstuff.com">Support</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="//cdn.jsdelivr.net/editor/0.1.0/editor.js"></script>
        <script src="//cdn.jsdelivr.net/editor/0.1.0/marked.js"></script>
        <script src="/static/bootstrap.min.js"></script>
        <script src="/static/underscore.min.js"></script>
        <script src="/static/chart.js"></script>
        <script src="/static/global.js"></script>
        {% if not dnt %}
        {% if analytics_id and analytics_domain %}
        <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', '{{ analytics_id }}', '{{ analytics_domain }}');
        ga('require', 'displayfeatures');
        ga('send', 'pageview');
        </script>
        {% endif %}
        {% endif %}
        {% block scripts %}{% endblock %}
    </body>
</html>